<a href="https://colab.research.google.com/github/shrutiparmar2003/Machine-learning-with-Scikit-Learn-Tensorflow-and-Keras/blob/main/Training_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
m=100 #taking 100 instances or sample dataset points
X=2*np.random.rand(m,1)                               #rand(m, 1) creates an array with m rows and 1 column filled with random numbers between 0 and 1.
                                         #So, if m = 100, this line would create an array of shape (100, 1), with each entry being a random number between 0 and 2
y=4+3*X+np.random.rand(m,1)       #creates our target variable y, based on the formula y=4+3*X+np.random.rand(m,1)  with a bit of random noise (np.random.randn) added for variation

In [4]:
X_b = np.c_[np.ones((m, 1)), X] #the matrix X has m rows and 2 columns ,1st column has been set to all 1s and second to all random values of m

In [5]:
theta_best=np.linalg.inv(X_b.T@X_b)@X_b.T@y

In [6]:
print(theta_best)

[[4.51359766]
 [2.98323418]]


In [7]:
from sklearn.linear_model import LinearRegression
lin_reg_model=LinearRegression()
lin_reg_model.fit(X,y)
print("Intercept: ",lin_reg_model.intercept_)
print("Coefficient: ",lin_reg_model.coef_)


Intercept:  [4.51359766]
Coefficient:  [[2.98323418]]


In [8]:
#gradient descent and its types done from book.It was mere understanding of the concept and the time taken by each type of descent to find the global minimum value of theta so that the cost function evaluates to minimum.
#Cost function is the difference between the predicted values and the actual values.


In [9]:
#POLYNOMIAL REGRESSION
#What we are trying to do here is to fit a linear model to a nonlinear data.

np.random.seed(42)
m=100
X=6*np.random.rand(m,1)-3 #adding some random noise also to x
y=0.5*X**2 + X+2+ np.random.randn(m,1)


In [10]:
from sklearn.preprocessing import PolynomialFeatures
poly_features=PolynomialFeatures(degree=2,include_bias=False)
X_poly=poly_features.fit_transform(X)
print(X[0]) #this is the value of x
print(X_poly[0]) #this will contain value of x plus value of x square

[-0.75275929]
[-0.75275929  0.56664654]


In [11]:
#Now you can fit a linear regression model to this data
lin_reg=LinearRegression()
lin_reg.fit(X_poly,y)
print(lin_reg.intercept_, lin_reg.coef_)

[1.78134581] [[0.93366893 0.56456263]]


In [12]:
#the model predicts the equation = 0.56x square + 0.933x+ 1.78134 which is close to the value of y that we assumed.

In [13]:
#REGULARIZED LINEAR MODEL
#regularization is a technique to prevent a model from overfitting a data. This overfitting happens when the model focuses too uch  on one feature that is gives more weight
#to one feature and ignores others. Therefore we add a regularization term to the cost function to constarint the weights or balance the weights.

In [14]:
#RIDGE REGRESSION
from sklearn.linear_model import Ridge
ridge_reg=Ridge(alpha=0.1,solver="cholesky")
ridge_reg.fit(X,y)
ridge_reg.predict([[1.5]])


array([[4.82899748]])

In [15]:
from sklearn.linear_model import SGDRegressor
sgd_reg=SGDRegressor(penalty="l2",alpha=0.1/m, tol=None,max_iter=1000,eta0=0.01,random_state=42)
sgd_reg.fit(X,y)
sgd_reg.predict([[1.5]])


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([4.82830117])

In [16]:
from sklearn.linear_model import Lasso
lasso_reg=Lasso(alpha=0.1)
lasso_reg.fit(X,y)
lasso_reg.predict([[1.5]])

array([4.77621741])

In [17]:
from sklearn.linear_model import SGDRegressor
sgd_reg=SGDRegressor(penalty="l1",alpha=0.1)
sgd_reg.fit(X,y)
sgd_reg.predict([[1.5]])


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([4.75312959])

In [18]:
#Elastic net regression
from sklearn.linear_model import ElasticNet
elastic_net=ElasticNet(alpha=0.1,l1_ratio=0.5)
elastic_net.fit(X,y)
elastic_net.predict([[1.5]])


array([4.78114505])

In [23]:
# Early stopping
from copy import deepcopy
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline

#splitting the dataset
X_train,X_valid,y_train,y_valid=train_test_split(X,y,test_size=0.2,random_state=42)
preprocessing=make_pipeline(PolynomialFeatures(degree=90,include_bias=False),StandardScaler())
X_train_prep=preprocessing.fit_transform(X_train)
X_valid_prep=preprocessing.transform(X_valid)
sgd_reg=SGDRegressor(penalty=None,eta0=0.002,random_state=42)
n_epochs=500;
best_valid_rmse=float('inf')

for epoch in range(n_epochs):
  sgd_reg.partial_fit(X_train_prep,y_train)
  y_valid_predict=sgd_reg.predict(X_valid_prep)
  val_error=mean_squared_error(y_valid,y_valid_predict,squared=False)
  if val_error<best_valid_rmse:
    best_valid_rmse=val_error
    best_model=deepcopy(sgd_reg)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the functi